### ISSUE TITLE
Plugins.Device is undefined

### ISSUE THREAD

**Issue by filifunk** [GrayHat12/gray-geolocation#1]
Hi thanks for this project.  I'm hoping it can solve my android geolocation issues.

I followed your example code and got this:

```Uncaught (in promise) TypeError: _capacitor_core__WEBPACK_IMPORTED_MODULE_15__.Plugins.Device is undefined```

Also, my MainActivity.Java looks different than yours:

```
package com.ionicapp.ionicapp;

import com.getcapacitor.BridgeActivity;

import com.grayhat.geolocation.GrayGeolocation;

public class MainActivity extends BridgeActivity {
    add(GrayGeolocation.class)
}

```
How do I get mine to work?  Do I have to install Plugins somehow?

**Comment by GrayHat12** [comment]
I believe the `Plugins.Device` way is deprecated now. You can find the newer way to getInfo from [this](https://capacitorjs.com/docs/apis/device) link. I should probably update the documentation.

**Comment by GrayHat12** [comment]
You will now need to:
* Install : `npm i @capacitor/device`
* Import : `import { Device } from "@capacitor/device";`
* Get Info : `await Device.getInfo();`
